"""new base configuration entirely

Revision ID: 0753228fd1bf
Revises:
Create Date: 2024-01-07 15:03:47.880119

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0753228fd1bf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
