"""added join_tables for many to many relations, new base

Revision ID: 6faada7ddee4
Revises:
Create Date: 2024-01-23 00:16:06.363375

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6faada7ddee4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
